# ========== 资料栏 ========== #
# 头像路径
avatar: /avatar/kumamon.jpg
# 博主名字，不填写该字段则默认采用Hexo配置文件中的author字段
author: jiangyilin
# 博客签名
signature: xxxx
# 社交账号
social:
  email: 12345@qq.com
  github: //github.com/fi3ework
  weibo:
  # zhihu:
  # facebook:
  # twitter:
  # instagram:
  # stack-overflow:
  # linkedin:
# 友链
friends:
  friendA: //www.baidu.com
  friendB: //www.google.com
  # friendC :
# about页面  
about:
  enable: true
  image: '/intro/about-page.jpg'

# ========== 站点 ========== #
# 网站的title，每篇文章后面也会加上此字段利于SEO
SEO_title: 我的blog
# 显示在网站banner上的主标题
main_title: 我的blog
# 显示在网站banner上的副标题
subtitle: it's better to burn out than to fade away
# 主页banner的背景图片
site_header_image: 'http://oumn0o088.bkt.clouddn.com/intro-desktop.jpg'
# 文章页的默认背景图片
post_header_image: 'http://oumn0o088.bkt.clouddn.com/post-bg.jpg'
# 404页的背景图片
_404_image: 'http://oumn0o088.bkt.clouddn.com/404.jpg'

# ========== 评论插件 ========== #
# 目前只支持一键添加livere评论（因为懒），其他评论插件可自行添加在post.ejs模板中的</main>标签前。
comment:
  # 将你的livere的uid填入以下字段
  livere:

# ========== 统计 ========== #
# 是否开启不蒜子统计
busuanzi: false
# 百度统计(填写siteID)
baidu_analytics:
# Google统计(填写siteID)
#google_analytics:
# CNZZ统计
#CNZZ_analytics:

# ========== 其他 ========== #
# favicon
favicon: /assests/favicon.ico
# 首页的文章摘要字数(默认300)
truncate_length:
